### ISSUE TITLE
Page not Found

### ISSUE THREAD

**Issue by russellseymour** [silexphp/Silex-Skeleton#24]
Hello,

I have just cloned this project to understand how the profiler works, but when I try to access the 'index_dev.php' page I get an HTTP 404 error with a dialog box asking if I want to open the profiler.

It then takes me to a another page and it states that 'Page not found'.

I had to create a 'main.css' page as that was missing, but that has not fixed the problem.
I can see that lots of files are being created in the /var/cache directory but I do not see the toolbar or any useful information.

I am sure I am missing something obvious.

thanks, Russell

**Comment by mTorres** [comment]
I've managed to reproduce this error and in fact it is an issue with Nginx proposed configuration. I've copied and adapted the [Symfony's one](http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html#nginx) and created a [pull request on Silex repo](https://github.com/silexphp/Silex/pull/1185) to solve this issue.

My proposal is as follows:

    server {
        server_name domain.tld www.domain.tld;
        root /var/www/project/web;
    
        location / {
            # try to serve file directly, fallback to front controller
            try_files $uri /index.php$is_args$args;
        }
        
        location ~ ^/(index|index_dev)\.php(/|$) {
            # the ubuntu default
            fastcgi_pass   unix:/var/run/php5-fpm.sock;
            # for running on centos
            #fastcgi_pass   unix:/var/run/php-fpm/www.sock;
    
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param HTTPS off;
        
            # Prevents URIs that include the front controller. This will 404:
            # http://domain.tld/index.php/some-path
            # Enable the internal directive to disable URIs like this
            # internal;
        }
    
        error_log /var/log/nginx/project_error.log;
        access_log /var/log/nginx/project_access.log;
    }

**Comment by mTorres** [comment]
@fabpot, I think you can safely close this one as [e9bd89b](https://github.com/silexphp/Silex/commit/e9bd89bb60cfeaebbab8f1d3572d733b636bfb4e) is merged

**Comment by fabpot** [comment]
@mTorres Thanks for the heads up.

**Comment by ashorlivs** [comment]
In case somebody else encounters the same error and runs Apache, put this in your .htaccess:

```
<IfModule mod_rewrite.c>
    Options -MultiViews

    RewriteEngine On
    #RewriteBase /path/to/app
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [QSA,L]
</IfModule>
```
