### ISSUE TITLE
update to Silex 2 

### ISSUE THREAD

**Issue by rizerzero** [silexphp/Silex-Skeleton#34]
Hi sir , 
Will you update this to work with silex 2 
Thank you .

**Comment by lluisi** [comment]
Please take a look on the [composer.json](https://github.com/silexphp/Silex-Skeleton/blob/master/composer.json), you will see that silex2 is been used
```javascript
"silex/silex": "~2.0@dev",
```

**Comment by mTorres** [comment]
Yeah, this should be closed.
