### ISSUE TITLE
composer run timeout

### ISSUE THREAD

**Issue by olessavluk** [silexphp/Silex-Skeleton#38]
Hi!
There is problem with `composer run` command. After 5 minutes php server terminated with message:

    [Symfony\Component\Process\Exception\ProcessTimedOutException]             
    The process "php -S localhost:8888 -t web web/index_dev.php" 
    exceeded the timeout of 300 seconds.                            

This is because of composer's default timeout (set to 300s by default https://getcomposer.org/doc/03-cli.md#composer-process-timeout).

Is there any way to disable\increase this timeout?

**Comment by stopfstedt** [comment]
try setting the `COMPOSER_PROCESS_TIMEOUT` env var on the command line, like so:

```bash
COMPOSER_PROCESS_TIMEOUT=600 composer run
```

of relevance in case you're on Windows: http://stackoverflow.com/questions/24950813/how-to-use-composer-process-timeout

**Comment by julianfox** [comment]
Hey, any way to set up unlimited composer process directly in composer.json ?
