### ISSUE TITLE
UrlGeneratorServiceProvider in Silex 2.0 dev

### ISSUE THREAD

**Issue by albmaso** [silexphp/Silex-Skeleton#39]
I'm testing SIlex version 2.0 dev.
I can see that UrlGeneratorServiceProvider not exist in this version. What alternative can I use, for example in my Twig templates for using path() function ?

Thanks

**Comment by Jbekker** [comment]
If you have the RoutingServiceProvider and TwigServiceProvider enabled it should work.

**Comment by albmaso** [comment]
My error was related with a bad named route in bind calling. Now it works

thanks
