### ISSUE TITLE
Serving static files

### ISSUE THREAD

**Issue by kpyorala** [silexphp/Silex-Skeleton#40]
I needed to add this to index_dev.php and index.php to serve static files:

http://silex.sensiolabs.org/doc/web_servers.html#php-5-4

**Comment by olessavluk** [comment]
Also, `$_SERVER['REQUEST_URI']` is url encoded. So you need to decode it before using.
You should write following:
```php
$filename = __DIR__.preg_replace('#(\?.*)$#', '', urldecode($_SERVER['REQUEST_URI']));
```
