### ISSUE TITLE
 WebProfilerServiceProvider Error

### ISSUE THREAD

**Issue by Hadrien45** [silexphp/Silex-Skeleton#44]
Hi,

I have a bug with the WebProfilerServiceProvider (line 71)
Notice: Indirect modification of overloaded element of Silex\Application has no effect

Installation : 
I clone the Silex-Skeleton repository branch 1.1,
I update vendor with composer,
I launch app in dev environment (index_dev.php) and this error appears : 

ContextErrorException in WebProfilerServiceProvider.php line 71: Notice: Indirect modification of overloaded element of Silex\Application has no effect

Thanks

**Comment by fabpot** [comment]
fixed now.

**Comment by Hadrien45** [comment]
Thanks
