### ISSUE TITLE
Add a SilexRequirements class and and web/check.php

### ISSUE THREAD

**Issue by mickaelandrieu** [silexphp/Silex-Skeleton#45]
I think this kind of features available in Symfony standard can be usefull everywhere: https://github.com/symfony/symfony-standard/blob/2.8/app/SymfonyRequirements.php , I can make a pull request which check for the Silex requirements if you think this can be accepted. 

What do you think ?

**Comment by fabpot** [comment]
It's out of the scope of the skeleton, which should be just about providing the directory structure to get started.
