### ISSUE TITLE
Providers implements Pimple\ServiceProviderInterface instead of Silex\ServiceProviderInterface as stated in the documentation.

### ISSUE THREAD

**Issue by Ovski4** [silexphp/Silex-Skeleton#47]
Hi,

I'm trying to add a provider to my silex application, but I'm facing an issue.

I installed my project this way : composer create-project fabpot/silex-skeleton silex-skeleton ~2.0@dev

By reading the documentation, it says "Providers must implement the Silex\ServiceProviderInterface:"
But the ServiceProviderInterface is located in the Pimple vendor.
Looking at the providers ready for use, they implement Pimple\ServiceProviderInterface;

What am i missing? Can this skeleton be used as a normal silex application or are there some specificities?

Thanks

**Comment by Ovski4** [comment]
Hi again,

Just to state the obvious, I eventually implemented the Pimple\ServiceProviderInterface. I looked at the providers already existing and did the same for my own provider.
I'm not closing this issue as I would like to know if this si the right thing to do, and if so I guess this repo is ahead of the regular silex branch, which would explain why the documentation is outdated. If someone can confirm or deny and explain, I'll close this issue

**Comment by fabpot** [comment]
Indeed, the docs are not uptodate. Can you provide a fix?

**Comment by Ovski4** [comment]
Thank you for your answer.
Sure, I'll gladly create a pull request on the docs

**Comment by fabpot** [comment]
Thanks.

**Comment by Ovski4** [comment]
My bad, the docs are up to date on the master branch of the Silex repository.

The silex website is in sync with the 1.3 branch of the Silex repository, which is why it's outdated with the Silex-Skeleton repository (based on the master branch of Silex)

A simple warning on which docs to refer in order to work with the SilexSkeleton should be enough.
