### ISSUE TITLE
Class 'Silex\Provider\RoutingServiceProvider' not found

### ISSUE THREAD

**Issue by AlexL5** [silexphp/Silex-Skeleton#48]
Hi,

I start a new project and I've got this issue : 
Fatal error: Class 'Silex\Provider\RoutingServiceProvider' not found in ...\src\app.php on line 11.

Indeed, RoutingServiceProvider is missing from vendor\silex\silex\src\silex\Provider.

My composer.json : 
```
{
	"require": {
		"silex/silex": "~1.3"
	}
}
```

Have I made something wrong ?

(And i can't see the class in repository silexphp/Silex)
Thanks

**Comment by kabdessamad1** [comment]
update your composer.json and install 2.0.x-dev : "silex/silex": "2.0.x-dev",
