### ISSUE TITLE
The function "render" does not exist in "@WebProfiler/Profiler/layout.html.twig"

### ISSUE THREAD

**Issue by frzsombor** [silexphp/Silex-Skeleton#49]
With my fresh, clean install of Silex Skeleton, I've opened index_dev.php and instantly got an error:

Twig_Error_Syntax in ExpressionParser.php line 572:
The function "render" does not exist in "@WebProfiler/Profiler/layout.html.twig" at line 5

I've found that it is a known issue, and it's possible to fix it: https://github.com/silexphp/Silex-WebProfiler/issues/67
*( add `$app->register(new Silex\Provider\HttpFragmentServiceProvider());` in app.php )*

However I'm not sure it's good for beginners (like me) to instantly get an error in Silex Skeleton, with a new, clean project. Any plans to fix this?

**Comment by fabpot** [comment]
You were probably using the master branch of the skeleton, which is for the upcoming Silex 2.0.

**Comment by wcomnisky** [comment]
I'm getting this error using the 1.1 branch of the skeleton with the silex ~1.0
