### ISSUE TITLE
index.php not showing content

### ISSUE THREAD

**Issue by rogervila** [silexphp/Silex-Skeleton#50]
Hello,
When I work with index_dev.php everything works fine, but index.php is not showing anything.
I have deleted the cache but the problem persists.
What can I do?

Thank you.

**Comment by kabdessamad1** [comment]
The profiler cache ?

**Comment by rogervila** [comment]
@kabdessamad1 I fixed it deleting the full cache folder and also the browser cache using Onyx, not just the Firefox 
Thank you anyway!
