### ISSUE TITLE
Method "request" for object "Silex\Application" does not exist

### ISSUE THREAD

**Issue by webslash** [silexphp/Silex-Skeleton#51]
Hey

Every time I try to use something like:
{{ app.request.basepath }} in my twig templates.

I get this error: 
Method "request" for object "Silex\Application" does not exist in ...

How to fix this?

Thanks

**Comment by kabdessamad1** [comment]
If you are using the  silex skeleton then use 
{{ asset('path to your css') }}

**Comment by webslash** [comment]
@kabdessamad1 Cool, that works for assets, but how about things like:
 {{ app.request.cookies.get('exampleCookie') }}

**Comment by kabdessamad1** [comment]
im beginner in silex and for getting cookies i made this and added it to my app.php file

$app['twig'] = $app->extend('twig', function ($twig, $app) {
    $twig->addFunction(new \Twig_SimpleFunction('getCookie', function($cookie) use($app){
        $request = \Symfony\Component\HttpFoundation\Request::createFromGlobals();
        return $request->cookies->get($cookie);
    }));
    return $twig;
});

in your twig use {{ getCookie('cookie_name' }}

{% if getCookie('PHPSESSID') == '2dbba3ed8c2d00394ab05046954fbf4c' %}
       // code here
{% endif  %}

i guess you are using silex 2.0-dev you should use the stable version

**Comment by webslash** [comment]
Thanks @kabdessamad1 worked! :)

Why is this Silex-Skeleton using silex 2.0-dev by default, even though its not stable?
I'm assuming this Skeleton is mostly used by beginners, so giving an unstable start doesn't seem like a good idea..
@fabpot What's the reasoning behind this?

**Comment by kabdessamad1** [comment]
you can create your own skeleton its easy :)

**Comment by fabpot** [comment]
The master branch being the default is just a misconfiguration of the repo, fixing that now.
