### ISSUE TITLE
Getting the skeleton with composer giver an error

### ISSUE THREAD

**Issue by babdellhamid** [silexphp/Silex-Skeleton#54]
Hello,

When I try to get the Silex-Skeleton with composer as instructed in the description:

./composer.phar create-project Silex-Skeleton-1.1/ myapplication/

The following error message is given:

 [InvalidArgumentException]                                         
  Could not find package silex-skeleton-1.1/ with stability stable.

Moreover the the file composer.json does not seem to date

Can you help me please ?

**Comment by kabdessamad1** [comment]
Hi ,
the current version is 1.1.1 by default and you can copy/paste the correct commande from the read me :
https://github.com/silexphp/Silex-Skeleton/blob/1.1/README.rst

**Comment by babdellhamid** [comment]
Hello,

Thank you for the answer. It works correctly.
Sorry,

**Comment by kabdessamad1** [comment]
if so you can marked as closed :)
