### ISSUE TITLE
FatalErrorException in app.php - does php.ini need to have sth set?

### ISSUE THREAD

**Issue by pacid** [silexphp/Silex-Skeleton#56]
I've just downloaded and trying to run Silex-Skeleton and get : 

FatalErrorException in app.php line 18:
Parse Error: syntax error, unexpected ';'
in app.php line 18
at {main}() in index_dev.php line 0

I'm running:
PHP 5.6.2 Development Server started at Tue Nov 10 09:58:33 2015

**Comment by mTorres** [comment]
Did you write some code? Line [18 on 1.1](https://github.com/silexphp/Silex-Skeleton/blob/1.1/src/app.php#L18) is user code (yours) and [on master](https://github.com/silexphp/Silex-Skeleton/blob/master/src/app.php#L18) is the closing of the twig extension definition so a ; must be there.

This must be closed as this is not an issue with the skeleton but the user code.

PS: To get general help, please use [StackOverflow with the Silex tag](http://stackoverflow.com/tags/silex/info).
