### ISSUE TITLE
Where is the "2.0.x-dev" branch?

### ISSUE THREAD

**Issue by Narno** [silexphp/Silex-Skeleton#59]
Some code was merged in the "2.0.x-dev" branch, but I can't find it now. Deleted?

i.e: https://github.com/silexphp/Silex-Skeleton/commit/d129ef4e4b32ff93cd80907fa413a586a213d142

**Comment by madebydavid** [comment]
That asset function was removed in [this commit](https://github.com/silexphp/Silex-Skeleton/commit/489fe0ad2c8270b03542c2132ad493d84999a64a) since the asset service provider was added in [this one](https://github.com/silexphp/Silex-Skeleton/commit/a88b05f09b10673aca6aa282adf15c4ca5468055)

**Comment by lyrixx** [comment]
It's "master". 
The commit message says "2.0" because it's use the branch alias of [composer](https://github.com/silexphp/Silex-Skeleton/blob/master/composer.json#L31) and because master mean nothing

**Comment by Narno** [comment]
@madebydavid, @lyrixx thanks a lot guys!
