### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by patchankito** [silexphp/Silex-Skeleton#68]
Salut,

juste pour vous signaler de la présence dans le README du provider "UrlGeneratorServiceProvider" dans la section "What's inside ?" alors qu'il n'est plus présent dans silex.

En tout cas merci pour ce skeleton, très utile en tant que formateur pour proposer aux élèves un socle solide où bâtir leurs applications.

Bonne route !

**Comment by fabpot** [comment]
fixed, thanks for the report.
